#!/usr/bin/env node

import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildArenaMap } from "../packages/shared/map/arena-map.source.mjs";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "..");
const generatedDirectory = path.join(
  repositoryRoot,
  "packages",
  "shared",
  "generated"
);
const generatedSourceDirectory = path.join(
  repositoryRoot,
  "packages",
  "shared",
  "src",
  "generated"
);
const checkOnly = process.argv.includes("--check");

const sourceMap = buildArenaMap();
const canonicalSource = JSON.stringify(sourceMap);
const contentHash = createHash("sha256")
  .update(canonicalSource)
  .digest("hex");
const arenaMap = {
  ...sourceMap,
  contentHash,
};

const jsonContents = `${JSON.stringify(arenaMap, null, 2)}\n`;
const typescriptContents = `/* This file is generated by scripts/generate-map.mjs. Do not edit. */
import type { ArenaMapDefinition } from "../mapTypes.js";

export const ARENA_MAP_GENERATED = ${JSON.stringify(arenaMap, null, 2)} as const satisfies ArenaMapDefinition;
`;

const rustString = (value) => JSON.stringify(String(value));
const rustFloat = (value) => {
  if (!Number.isFinite(value)) {
    throw new TypeError(`Cannot emit non-finite Rust float: ${value}`);
  }
  const rendered = Number.isInteger(value) ? `${value}.0` : String(value);
  return `${rendered}_f32`;
};
const rustVec3 = ([x, y, z]) =>
  `MapVec3 { x: ${rustFloat(x)}, y: ${rustFloat(y)}, z: ${rustFloat(z)} }`;
const rustStrings = (values) =>
  `&[${values.map((value) => rustString(value)).join(", ")}]`;

const rustAabbs = arenaMap.boxes
  .filter((item) => item.collision)
  .map(
    (item) => `    MapAabb {
        id: ${rustString(item.id)},
        center: ${rustVec3(item.center)},
        half_extents: ${rustVec3(item.size.map((value) => value / 2))},
        kind: ${rustString(item.kind)},
        material_id: ${rustString(item.materialId)},
        walkable: ${item.walkable},
        tags: ${rustStrings(item.tags)},
    },`
  )
  .join("\n");

const rustRamps = arenaMap.ramps
  .map(
    (item) => `    MapRamp {
        id: ${rustString(item.id)},
        min_x: ${rustFloat(item.minX)},
        max_x: ${rustFloat(item.maxX)},
        min_z: ${rustFloat(item.minZ)},
        max_z: ${rustFloat(item.maxZ)},
        base_y: ${rustFloat(item.baseY)},
        top_y: ${rustFloat(item.topY)},
        axis: ${rustString(item.axis)},
        ascending_positive: ${item.ascending === "positive"},
        material_id: ${rustString(item.materialId)},
        tags: ${rustStrings(item.tags)},
    },`
  )
  .join("\n");

const rustSpawns = arenaMap.spawns
  .map(
    (item) => `    MapSpawn {
        id: ${rustString(item.id)},
        position: ${rustVec3(item.position)},
        yaw: ${rustFloat(item.yaw)},
        zone: ${rustString(item.zone)},
        nav_waypoint_id: ${rustString(item.navWaypointId)},
        safe_radius: ${rustFloat(item.safeRadius)},
        cover_facing: ${rustFloat(item.coverFacing)},
    },`
  )
  .join("\n");

const rustPickups = arenaMap.pickups
  .map(
    (item) => `    MapPickup {
        id: ${rustString(item.id)},
        kind: ${rustString(item.kind)},
        position: ${rustVec3(item.position)},
        respawn_ticks: ${item.respawnTicks}_u32,
    },`
  )
  .join("\n");

const rustWaypoints = arenaMap.navWaypoints
  .map(
    (item) => `    MapNavWaypoint {
        id: ${rustString(item.id)},
        position: ${rustVec3(item.position)},
        neighbors: ${rustStrings(item.neighbors)},
        route: ${rustString(item.route)},
        tags: ${rustStrings(item.tags)},
    },`
  )
  .join("\n");

const rustContents = `// This file is generated by scripts/generate-map.mjs. Do not edit.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MapVec3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MapAabb {
    pub id: &'static str,
    pub center: MapVec3,
    pub half_extents: MapVec3,
    pub kind: &'static str,
    pub material_id: &'static str,
    pub walkable: bool,
    pub tags: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MapRamp {
    pub id: &'static str,
    pub min_x: f32,
    pub max_x: f32,
    pub min_z: f32,
    pub max_z: f32,
    pub base_y: f32,
    pub top_y: f32,
    pub axis: &'static str,
    pub ascending_positive: bool,
    pub material_id: &'static str,
    pub tags: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MapSpawn {
    pub id: &'static str,
    pub position: MapVec3,
    pub yaw: f32,
    pub zone: &'static str,
    pub nav_waypoint_id: &'static str,
    pub safe_radius: f32,
    pub cover_facing: f32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MapPickup {
    pub id: &'static str,
    pub kind: &'static str,
    pub position: MapVec3,
    pub respawn_ticks: u32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MapNavWaypoint {
    pub id: &'static str,
    pub position: MapVec3,
    pub neighbors: &'static [&'static str],
    pub route: &'static str,
    pub tags: &'static [&'static str],
}

pub const ARENA_MAP_SCHEMA_VERSION: u32 = ${arenaMap.schemaVersion}_u32;
pub const ARENA_MAP_ID: &str = ${rustString(arenaMap.id)};
pub const ARENA_MAP_CONTENT_HASH: &str = ${rustString(arenaMap.contentHash)};
pub const ARENA_TICK_RATE: u32 = ${arenaMap.tickRate}_u32;
pub const ARENA_MAX_COMBATANTS: usize = ${arenaMap.maxCombatants}_usize;
pub const ARENA_FLOOR_Y: f32 = ${rustFloat(arenaMap.world.floorY)};
pub const ARENA_KILL_Y: f32 = ${rustFloat(arenaMap.world.killY)};
pub const ARENA_PLAYER_RADIUS: f32 = ${rustFloat(arenaMap.world.playerRadius)};
pub const ARENA_PLAYER_HEIGHT: f32 = ${rustFloat(arenaMap.world.playerHeight)};
pub const ARENA_MAX_STEP_HEIGHT: f32 = ${rustFloat(arenaMap.world.maxStepHeight)};
pub const ARENA_MIN_SPAWN_SEPARATION: f32 = ${rustFloat(arenaMap.world.minSpawnSeparation)};
pub const ARENA_SPAWN_PROTECTION_TICKS: u32 = ${arenaMap.world.spawnProtectionTicks}_u32;
pub const ARENA_PLAYABLE_MIN: MapVec3 = ${rustVec3(arenaMap.world.playableBounds.min)};
pub const ARENA_PLAYABLE_MAX: MapVec3 = ${rustVec3(arenaMap.world.playableBounds.max)};

pub const ARENA_AABBS: &[MapAabb] = &[
${rustAabbs}
];

pub const ARENA_RAMPS: &[MapRamp] = &[
${rustRamps}
];

pub const ARENA_SPAWNS: &[MapSpawn] = &[
${rustSpawns}
];

pub const ARENA_PICKUPS: &[MapPickup] = &[
${rustPickups}
];

pub const ARENA_NAV_WAYPOINTS: &[MapNavWaypoint] = &[
${rustWaypoints}
];
`;

const outputs = [
  [
    path.join(generatedDirectory, "arena-map.json"),
    jsonContents,
  ],
  [
    path.join(generatedSourceDirectory, "arenaMap.generated.ts"),
    typescriptContents,
  ],
  [
    path.join(generatedDirectory, "arena_map.rs"),
    rustContents,
  ],
];

if (checkOnly) {
  let mismatch = false;
  for (const [filePath, expected] of outputs) {
    let actual = "";
    try {
      actual = await readFile(filePath, "utf8");
    } catch {
      mismatch = true;
      console.error(`Missing generated map artifact: ${path.relative(repositoryRoot, filePath)}`);
      continue;
    }
    if (actual !== expected) {
      mismatch = true;
      console.error(`Outdated generated map artifact: ${path.relative(repositoryRoot, filePath)}`);
    }
  }
  if (mismatch) process.exitCode = 1;
} else {
  await mkdir(generatedDirectory, { recursive: true });
  await mkdir(generatedSourceDirectory, { recursive: true });
  for (const [filePath, contents] of outputs) {
    let current = "";
    try {
      current = await readFile(filePath, "utf8");
    } catch {
      // The artifact is new.
    }
    if (current !== contents) {
      await writeFile(filePath, contents, "utf8");
      console.log(`Generated ${path.relative(repositoryRoot, filePath)}`);
    }
  }
}
